### ISSUE TITLE
A well-defined MLTable file was not found at the root of the selected folder.

### ISSUE THREAD

**Issue by itmilos** [MicrosoftLearning/AI-900-AIFundamentals#30]
data/ml/daily-bike-share.csv 

<img width="675" alt="Screenshot 2023-05-21 at 12 19 54" src="https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/2508127/ac776f38-3ee4-49a1-89c9-3ae66dc6ce4b">

**Comment by sherzyang** [comment]
@itmilos, please use the provided link in the instructions rather than the link you are using to complete the lab. Thanks! 

In this section of the instructions: 
https://microsoftlearning.github.io/AI-900-AIFundamentals/instructions/02-module-02.html#create-a-data-asset

Please use this link from the instructions: 
https://aka.ms/bike-rentals
