### ISSUE TITLE
 Analyze text with the Text Analytics Service

### ISSUE THREAD

**Issue by ParthasarathiReddy6621** [MicrosoftLearning/AI-900-AIFundamentals#44]
# Module:  week1
#### Step: 03

Description of issue
getting this error when compiled "speaking-clock.ps1"
 13 |  $result = Invoke-RestMethod -Method Post `
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Name or service not known
Repro steps:

1.
1.
1.

**Comment by Mihai-Ac** [comment]
Hello @ParthasarathiReddy6621 

I have tried with both a **Speech** service and a **Cognitive Services** resources, I ran through all the steps and I wasn´t able to reproduce your error. 

The error message “Name or service not known” typically occurs when the Invoke-RestMethod command is unable to resolve the hostname specified in the URL. This could be due Proxy issues (if you are behind a proxy you will need to update  PowerShell´s proxy settings) or there is a connectivity issue with your environment (check Virtual network settings, security groups and firewall , so that they don´t block the URL), or even a temporary network issue.

I would suggest trying running this command in Powershell to delete the folder : `rm -r ai-900 -f`, clone again the repo (to make sure there are no issues with the speaking-clock file) , create a resource , update the key and region and try again. Also, makesure you have a stable network connection without any firewalls or security group rules that might block internet access.

**Comment by sherzyang** [comment]
@Mihai-Ac, thanks so much for the response!
@ParthasarathiReddy6621, if you are still having trouble, one of the common errors with speech is that you need to enter the location (for example, _eastus_) alongside your key. You could be getting an error because you are trying to use your key and endpoint.

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/19577448/94a31a62-9508-44e8-a89b-0648e9aa5dfe)

Additionally, you will want to make sure the location is copied and pasted exactly as it is displayed in Azure: 
![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/19577448/0663cb3f-a674-45dd-8593-3c9e28e5d963)

Hope that helps!
